### ISSUE TITLE
Decoded bool always 1 (true)

### ISSUE THREAD

**Issue by charles-liu** [vitelabs/soliditypp-vscode#18]
It comes from a vite.js issue: 

https://github.com/vitelabs/vite.js/issues/35 

Update vite.js dependency version to fix.

**Comment by niklr** [comment]
Maybe this is related to https://github.com/vitelabs/soliditypp/issues/4 ?

**Comment by charles-liu** [comment]
> Maybe this is related to [vitelabs/soliditypp#4](https://github.com/vitelabs/soliditypp/issues/4) ?

Yes, it's a duplicate of this one.

**Comment by charles-liu** [comment]
fixed in https://github.com/vitelabs/soliditypp-vscode/commit/359b36850102ea61c50649ef0ec7505045da3b71
